### ISSUE TITLE
Why `apt-get update` each time?

### ISSUE THREAD

**Issue by gau1991** [niteshsabankar/rtCamp-shell-script#3]
Why you to do `apt-get update` before each package installation, its always better to do only once, it will save your script time

**Comment by niteshsabankar** [comment]
Yes, you are right. Initially i was adding repo for each package. That is why I was updating repo every time. But, then I removed commands for adding repo because it can cause duplication, but unfortunately missed putting apt-get update command out of loop. Eventually I have made changes.
